yannh/kubeconform

- Readme.md
- scripts/openapi2jsonschema.py
This allows an alternative output file name format for the script, I wanted to use it with `kubeval` which is `{kind}-{group}-{version}`.
It may be the default for `kubeconform` as well (I haven't tested, but I have seen your issue to merge the 2 projects and I hope it will be considered seriously).
The `kindSuffix` part of the code I believe:
https://github.com/yannh/kubeconform/blob/9a56fc4176b6f917c6758b462b7b08a3dac3f518/pkg/registry/registry.go#L35-L41
https://github.com/instrumenta/kubeval/blob/529b532b1ea1ea002b1362640c0d52edcc02fc57/kubeval/kubeval.go#L75-L81
Thank you! ❤️
> scripts: Support for alternative filename format

- scripts/openapi2jsonschema.py
The files needs to be written in the for-loop, else only the last version of the list is written.
> scripts: Fix creation of schema from multi-version CRD

- acceptance.bats
- cmd/kubeconform/main.go
Should fix https://github.com/yannh/kubeconform/issues/27 and address https://github.com/yannh/kubeconform/pull/41
Only try to read from stdin when no other files/folders are passed to kubeconform
> Only read from stdin when no other files/folders given

- scripts/openapi2jsonschema.py
for yaml files with a structure like
```yaml
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
```
to avoid
```bash
Traceback (most recent call last):
File "kubeconform/scripts/openapi2jsonschema.py", line 117, in <module>
if "kind" not in y:
TypeError: argument of type 'NoneType' is not iterable
```
> Skip empty yaml docs

- Readme.md
- fixtures/cache/77d0b166bfea92a805efc479e183f115
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/registry/registry.go
- pkg/validator/validator.go
This should fix #59 
Note that in some cases this might be backwards incompatible. Maybe still doesn't warrant a major version bump :thinking:
> Validate against master by default, not 1.18.0

- .gitignore
- pkg/validator/validator.go
- pkg/validator/validator_test.go
Fixes #67
To expose the underlying issue, I refactored the `validator` test to exercise the actual code that finds the schema to perform validation.
Additional test scenarios were included.
> Properly handle successful http requests to registries sending invalid schema responses

- Dockerfile
- Makefile
- go.mod
Update to the [latest go1.17](https://blog.golang.org/go1.17)
> build: bump to use go1.17

- Readme.md
- acceptance.bats
- pkg/registry/http.go
This PR enables support for http_proxy environment variable as described in the function description https://pkg.go.dev/net/http#ProxyFromEnvironment
Test without proxy environment variable: 
` ./bin/kubeconform fixtures
fixtures/crd_schema.yaml - CustomResourceDefinition trainingjobs.sagemaker.aws.amazon.com failed validation: failed downloading schema at https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone/customresourcedefinition-apiextensions-v1beta1.json: Get "https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone/customresourcedefinition-apiextensions-v1beta1.json": dial tcp 185.199.111.133:443: connect: connection refused`
Test with proxy environment set: 
`
https_proxy=proxy.local:8080 ./bin/kubeconform fixtures …
> FIX: enable http_proxy environment variable

- scripts/openapi2jsonschema.py
...and `validation.openAPIV3Schema` if no `schema` under a version.
CRD can have multiple versions with multiple schemas, but versions can also share the
same schema.
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#specify-multiple-versions
> scripts: Check versions before version

- scripts/openapi2jsonschema.py
This makes it easy for generating specs out of all crds that are deployed to a cluster by simply running something like 
```
kubectl get crds -o yaml > crds.yaml
python3 openapi2jsonschema.py crds.yaml
```
> Also support items elements in yaml

- acceptance.bats
- pkg/resource/files.go
- pkg/resource/stream.go
This allows bufio.scanner to resize the read buffer up from 4MB up to 256MB if necessary. Fixes #57
> Support for larger files

- .goreleaser.yml
- Readme.md
- cmd/kubeconform/main.go
- pkg/config/config.go
- pkg/config/config_test.go
This will output the version based off the git tag, e.g.:
```
» ./bin/kubeconform -v
development
```
> Add -v flag to output version

- pkg/output/tap.go
- pkg/output/tap_test.go
- pkg/resource/resource.go
This is an improvement suggestion for the TAP output. With only the resource kind in the output, it can be impossible to know which resource is being validated:
```
ok 48 - stdin (RoleBinding)
ok 49 - stdin (RoleBinding)
ok 50 - stdin (RoleBinding)
ok 51 - stdin (RoleBinding)
```
This PR replaces the resource `kind` by a "qualified" resource name formatted `version/kind/namespace/name`: 
```
ok 48 - stdin (rbac.authorization.k8s.io/v1/RoleBinding/ns1/admin)
ok 49 - stdin (rbac.authorization.k8s.io/v1/RoleBinding/ns2/admin)
ok 50 - stdin (rbac.authorization.k8s.io/v1/RoleBinding/ns3/admin)
ok 51 - stdin (rbac.authorization.k8s.io/v1/RoleBinding/ns4/admin)
```
It also adds the signature to skipped resources:
```
ok 25 #skip - stdin
```
```
ok 24 - stdin …
```
> feat(output/tap): Output qualified resource name

- scripts/openapi2jsonschema.py
Equal sign (=) was not parsed properly by pyyaml.
Added constructor to parse equal sign as string.
Related issue: https://github.com/yannh/kubeconform/issues/103
> add constructor to handle equal sign (=)

- acceptance.bats
- pkg/config/config.go
Currently, if flag parsing fails, kubeconform exits with status 2 but no error message. This is because `ExitOnError` means `flags.Parse` actually calls `os.Exit` directly, rather than returning the error to the caller, which seems to have been what the rest of the program assumes. In combination with `flags.SetOutput`, the error message is written to a buffer which is never printed to the user.
This PR changes to `ContinueOnError`, which instead returns the error, leading to the buffer with the error message to be printed before exiting.
As a note, it also means the exit code will be 1 instead of 2 on flag parse errors, since that is what is currently done in `realMain` on errors from `config.FromFlags`. Not sure if this is something that would be considered a breaking change?
> fix: change flag parse error handling to return errors instead of exiting

- Readme.md
- acceptance.bats
- fixtures/duplicate_property.yaml
- pkg/config/config.go
- pkg/validator/validator.go
- pkg/validator/validator_test.go
- site/content/docs/usage.md
- site/public/docs/usage/index.html
Prevents specifying duplicate keys using
UnmarshallStrict: https://pkg.go.dev/gopkg.in/yaml.v2#UnmarshalStrict
> Forbid duplicate keys in strict mode

- Readme.md
- pkg/registry/registry.go
Hi!
I'd like to add support for schema-locations that contain multiple schemas divided by the name of the groups those schemas belong to. This can be very useful for testing CRDs.
What do you think?:)
> add {{ .Group }} variable to schema location options

- pkg/cache/ondisk.go
Use a stronger hash since md5 is generally discouraged at this point.
> Upgrade hash to sha256.

- Readme.md
- cmd/kubeconform/main.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/registry/http.go
- pkg/registry/http_test.go
- pkg/registry/local.go
- pkg/registry/registry.go
- pkg/validator/validator.go
When using -schema-location, it is sometimes difficult to understand why kubeconform fails to find the appropriate resource schema. This PR adds a -debug parameter that prints information on where Kubeconform tries to download schemas and which schema it will use for validation.
> Add debug information to help understand failures finding schemas

- Readme.md
- cmd/kubeconform/main.go
- pkg/config/config.go
CPU Profiling is only used for development purposes, and should not be exposed directly to the user via a flag. It can not be enabled via Environment variable.
> Do not expose internal CPU profiling option as flag

- Readme.md
- acceptance.bats
- pkg/config/config.go
- pkg/resource/resource.go
- pkg/validator/validator.go
- pkg/validator/validator_test.go
This is improving the `skip` or `reject` functionality allowing to provide the full GroupVersionKind encoding for resources to be skipped.
The functionality is useful in scenarios in which specific versions of certain resources should always be rejected and/or to allow more fine-grained control of the skip logic.
Unlike the GKV encoding [implemented in the upstream Kubernetes project](https://github.com/kubernetes/apimachinery/blob/3c16f3dcfb0b7876b1e5cc7190cd54fd0c50489c/pkg/apis/meta/v1/group_version.go#L92-L94), the APIVersion and Kind fields are separated by `/` to allow the concatenation of multiple arguments by `,`.
> Allow to skip resources using the GVK notation

- Readme.md
- scripts/openapi2jsonschema.py
I wanted to "just" add the info regarding the CRDs-catalog and how it's working with kubeconform, and I ended up using this opportunity to make some structure updates to the readme, based on the issues that have been open lately on this project.
> update readme structure and info 

- .github/workflows/main.yml
- .goreleaser.yml
- Makefile
This is useful when contributors want to test their pull request. And even they could use their pull request before it got merged.
> feat: support to set an alternative image owner

- pkg/output/json.go
- pkg/output/json_test.go
- pkg/validator/validator.go
```
{
"resources": [
{
"filename": "./fixtures/invalid.yaml",
"kind": "ReplicationController",
"name": "123",
"version": "v1",
"status": "statusInvalid",
"msg": "problem validating schema. Check JSON formatting: jsonschema: '/metadata/name' does not validate with https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone/replicationcontroller-v1.json#/properties/metadata/properties/name/type: expected string or null, but got number",
"validationErrors": [
{
"Path": "/properties/metadata/properties/name/type",
"Message": "expected string or null, but got number"
},
{
"Path": "/properties/spec/properties/replicas/type",
"Message": "expected integer or null, but got string"
}
]
}
],
"summary": {
"valid": 0,
"invalid": 1,
"errors": 0,
"skipped": 0
}
}
```
> Try to expose JSON paths

- scripts/Dockerfile.bats
- scripts/acceptance.bats
- scripts/openapi2jsonschema.py
Fixes #157
not the best implementation, but the pr has the minimal changes required in order to run this script on MAC without an issue. If the pr is approved, will edit the README as well
> support disabling ssl validation in openapi2jsonschema.py

- pkg/validator/validator.go
- pkg/validator/validator_test.go
Expose property path in validated document instead of location in schema, so it will be possible to point user to exact location.
xref https://github.com/yannh/kubeconform/issues/156
https://github.com/yannh/kubeconform/pull/173
> fix: expose error instance path instead of schema path

- .goreleaser.yml
- Dockerfile-alpine
Instruct goreleaser to also build arm64 images.
> Add support for Arm64 Docker images

- Readme.md
The in page link to the CustomResourceDefinition (CRD) Support section is not working
> Fix anchored link on Readme.md

- .github/workflows/main.yml
- .goreleaser.yml
Compare (on a m1 mac mini)
```
> docker run ghcr.io/yannh/kubeconform:v0.6.1 -v            
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
v0.6.1
```
with
```
> docker run ghcr.io/denisa/kubeconform:v0.6.3-dna.7 -v      
v0.6.3-dna.7
```
Note that I followed [GoReleaser build multi arch Docker Images](https://blog.devgenius.io/goreleaser-build-multi-arch-docker-images-8dd9a7903675) for the `latest` tag.
> Fix for 196: Multi-architecture image

- pkg/output/output.go
- Add missing 'junit' and 'pretty' output formats.
- Use quotes vs. backticks around command name
Note:
* I can revert the change removing the backticks, or, if you prefer, I could bold it, which might look better?
* I don't know if you want `output` or `-output` vs `outputFormat`? The user typically invokes the format using `-output`, I think.
* Could also make this a data structure and try to DRY it up a little, to make the error self-update?
> fix: add missing output formats in error message

- scripts/openapi2jsonschema.py
This is an alternative way to fix #130.
Instead of changing the `group` variable content, this commit adds
a new variable `fullgroup` that does not split the group components.
With this, users can specify the filename format like:
FILENAME_FORMAT='{fullgroup}-{version}-{kind}'
> Fix #130 in a backward-compatible way

- Makefile
- pkg/output/junit.go
- pkg/output/junit_test.go
This work should fix #246  - it also makes the Junit output deterministic, making it much easier to test.
> Fix junit output, also ensure junit output is deterministic

- pkg/config/config.go
- pkg/config/config_test.go
This should be a simple fix to #256 
Two additional test cases were implemented to check some cases of possible input value patterns.
The fix itself is realized within the splitCSV function, which now by default replaces all " " by "".
I'm aware, that this might not be the most suitable place for this fix. 
I thought of implementing it in one of the higher level function but was not sure about implications.
Feel free to comment of course :)
> Sanitize csv strings

- Makefile
- go.mod
Follow up to https://github.com/yannh/kubeconform/pull/268
> Update go version in go.mod

- pkg/validator/validator.go
- pkg/validator/validator_test.go
Currently, Validate and ValidateWithContext always returns a result with status `Empty` and a `missing 'kind' key` error as the final item in the returned slice.
This is because ValidateWithContext currently will parse the output of `resourcesChan`, even when the context is finished and we get back a default `Resource` struct.
This PR modifies the code to skip validating this case.
> Stop validating output of closed channel in Validate
